#!/usr/bin/env python

import os
import sys

print "testing1..."
os.environ['DJANGO_SETTINGS_MODULE'] = 'askbot_devel.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'askbot_devel'))
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

print "testing2..."
import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
